# Generated by Django 4.0.1 on 2024-11-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lote', models.CharField(max_length=25, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('etapa', models.CharField(default='-', max_length=25)),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('finalizado', 'Finalizado')], default='Iniciado', max_length=15)),
                ('producto', models.CharField(choices=[('prod A', 'Prod A'), ('prod B', 'Prod B'), ('prod C', 'Prod C')], default='No especificado', max_length=100)),
                ('tipo', models.CharField(choices=[('tipo 1', 'Tipo 1'), ('tipo 2', 'Tipo 2'), ('tipo 3', 'Tipo 3')], default=None, max_length=20)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=1, help_text='Cantidad en kg', max_digits=10, null=True)),
                ('calidad1', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, help_text='Calidad 1 (1-10)', null=True)),
                ('calidad2', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, help_text='Calidad 2 (1-10)', null=True)),
                ('usado', models.BooleanField(default=False)),
                ('tipo_lote', models.CharField(default='individual', max_length=20)),
                ('state', models.CharField(choices=[('Activo', 'Activo'), ('Desactivado', 'Desactivado')], default='Activo', max_length=20)),
                ('stock', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoteEnMezcla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_lotes.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Mezcla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mezcla', models.CharField(max_length=20)),
                ('cantidad_total', models.IntegerField()),
                ('lotes', models.ManyToManyField(through='gestion_lotes.LoteEnMezcla', to='gestion_lotes.Lote')),
            ],
        ),
        migrations.AddField(
            model_name='loteenmezcla',
            name='mezcla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_lotes.mezcla'),
        ),
    ]
