# Generated by Django 4.0.1 on 2024-11-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_lotes', '0002_alter_mezcla_nombre_mezcla'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezcla',
            name='despachada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mezcla',
            name='destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mezcla',
            name='stock_restante',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loteenmezcla',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_despacho', models.DateField(auto_now_add=True)),
                ('mezcla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='gestion_lotes.mezcla')),
            ],
        ),
    ]
