# Generated by Django 4.0.1 on 2024-11-12 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_lotes', '0003_mezcla_despachada_mezcla_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='fecha_despacho',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
