# Generated by Django 4.0.1 on 2024-11-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_lotes', '0004_alter_despacho_fecha_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezcla',
            name='producto',
            field=models.CharField(default='No especificado', max_length=100, null=True),
        ),
    ]
